### ISSUE TITLE
Images for README.md

### ISSUE THREAD

**Issue by shgodoroja** [mancunianetz/APNGb#1]
![world-cup-2014-42](https://cloud.githubusercontent.com/assets/2619031/21534194/c3e98950-cd63-11e6-84ed-043c16400368.png)
![world-cup-2014-42](https://cloud.githubusercontent.com/assets/2619031/21534196/c4b08316-cd63-11e6-8ae1-82aaf2a5cc95.gif)

**Comment by mancunianetz** [comment]
![screen shot 2016-10-19 at 02 27 41](https://cloud.githubusercontent.com/assets/2619031/19501210/e6165b54-95a3-11e6-9a31-7986e47fdeb7.png)
![screen shot 2016-10-19 at 02 27 33](https://cloud.githubusercontent.com/assets/2619031/19501213/e63edb92-95a3-11e6-9bf3-f9f3d5846541.png)
![screen shot 2016-10-19 at 02 27 30](https://cloud.githubusercontent.com/assets/2619031/19501212/e63d3738-95a3-11e6-89d0-2721676921fe.png)
![screen shot 2016-10-19 at 02 25 43](https://cloud.githubusercontent.com/assets/2619031/19501211/e63b3906-95a3-11e6-8d92-5b20bd16a668.png)

**Comment by shgodoroja** [comment]
![header-logo](https://cloud.githubusercontent.com/assets/2619031/21511755/0dcd98dc-cca5-11e6-86bf-d5b07a477523.png)

**Comment by shgodoroja** [comment]
![screen shot 2016-12-28 at 02 09 47](https://cloud.githubusercontent.com/assets/2619031/21534538/0464a1a4-cd69-11e6-8422-595f304cbefb.png)
![screen shot 2016-12-28 at 02 09 58](https://cloud.githubusercontent.com/assets/2619031/21534539/046583b2-cd69-11e6-82fb-a6d5bb5badda.png)
![screen shot 2016-12-28 at 02 10 03](https://cloud.githubusercontent.com/assets/2619031/21534540/0465b4b8-cd69-11e6-8c7d-d99f140a50d3.png)
![screen shot 2016-12-28 at 02 10 23](https://cloud.githubusercontent.com/assets/2619031/21534541/046616c4-cd69-11e6-8c61-d604cfe38e91.png)
![screen shot 2016-12-28 at 02 11 15](https://cloud.githubusercontent.com/assets/2619031/21534537/046473aa-cd69-11e6-8fde-35e7a79c307d.png)
![screen shot 2016-12-28 at 02 11 48](https://cloud.githubusercontent.com/assets/2619031/21534543/048288f4-cd69-11e6-9d65-0f5877309f78.png)
![screen shot 2016-12-28 at 02 11 56](https://cloud.githubusercontent.com/assets/2619031/21534542/0480acdc-cd69-11e6-97b0-aa7b25121990.png)
