### ISSUE TITLE
Binary won't opened – revoked certificate?

### ISSUE THREAD

**Issue by Canubiz** [mancunianetz/APNGb#4]
When trying to run the 2.0 binary on macOS 10.12.6 it won't open but macOS throws a message that this app should be moved to trash instead. When clicking the help button more details are provded saying the authorization for this certificate has been revoked.

**Comment by shgodoroja** [comment]
Hi @Canubiz, thanks for reporting this. I've released version 2.0.1 signed with a valid developer certificate.
