### ISSUE TITLE
download link to compiled binary?

### ISSUE THREAD

**Issue by wakest** [mancunianetz/APNGb#6]
don't see it anywhere. has it been taken down?

**Comment by shgodoroja** [comment]
Hey @wakest , have you checked [Releases](https://github.com/shgodoroja/APNGb/releases) page?

**Comment by wakest** [comment]
thanks! I didn't know to check in that tab. Might be useful to add a *Downloads* section to the main readme.md

**Comment by shgodoroja** [comment]
@wakest I've added a download reference next to app name at the top of home page.
